baseurl = "https://attilascp.github.io/"
title = "My Site"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
enableEmoji = true
[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Attila Pinter"
    avatar = "avatar.jpg"
    avatar2 = "avatar2.jpg"
    avatar3 = "avatar3.jpg"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    publicationYear = "2021"


# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/username"
    weight = 40

[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fas fa-robot'></i>"
    url = "blog/about/"
    weight = 20

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fas fa-rocket'></i>"
    url = "mailto:attila+gitscp@citapersada.sch.id"
    weight = 30
